In [1]:
import torch

In [3]:
x = torch.tensor([5,3])
y = torch.tensor([2,1])

x*y

tensor([10,  3])

In [5]:
x = torch.zeros([2,5])
x.shape

torch.Size([2, 5])

In [6]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [7]:
y = torch.rand([2,5])
y

tensor([[0.4977, 0.6987, 0.3876, 0.4699, 0.5238],
        [0.8324, 0.3334, 0.4248, 0.4425, 0.7398]])

In [8]:
y.view([1,10])

tensor([[0.4977, 0.6987, 0.3876, 0.4699, 0.5238, 0.8324, 0.3334, 0.4248, 0.4425,
         0.7398]])

In [9]:
y

tensor([[0.4977, 0.6987, 0.3876, 0.4699, 0.5238],
        [0.8324, 0.3334, 0.4248, 0.4425, 0.7398]])